name: Unit tests Zig

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      
      - name: Install LLVM (Linux)
        if: startsWith(matrix.runs-on, 'ubuntu')
        run: |
            sudo apt update
            sudo apt install -y wget
            sudo apt-add-repository "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-16 main"
            wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
            sudo apt update
            sudo apt install -y llvm-16

      - name: Install LLVM (MacOS)
        if: startsWith(matrix.runs-on, 'macos')
        run: brew install llvm

      - name: Build Summary
        run: |
            zig build test -fsummary -freference-trace
            zig build -Dexamples sum_module